using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ExperimnetalTypeSystem.Generator;

[Generator]
public sealed class ExperimentalTypingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax classDecl && classDecl.AttributeLists.Count > 0,
            static (ctx, _) => GetCandidate(ctx))
            .Where(static result => result is not null)
            .Select(static (result, _) => result!);

        context.RegisterSourceOutput(candidates.Collect(), static (spc, items) => Emit(spc, items));
    }

    private static Candidate? GetCandidate(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        if (!HasExperimentalTypingAttribute(classSymbol))
        {
            return null;
        }

        var intersections = new List<IntersectionInfo>();

        foreach (var member in classDecl.Members.OfType<PropertyDeclarationSyntax>())
        {
            if (context.SemanticModel.GetDeclaredSymbol(member) is not IPropertySymbol propertySymbol)
            {
                continue;
            }

            if (propertySymbol.Type.Name != "UnionType")
            {
                continue;
            }

            if (member.ExpressionBody?.Expression is null)
            {
                continue;
            }

            if (!TryGetUnionTypes(member.ExpressionBody.Expression, context.SemanticModel, out var unionTypes))
            {
                continue;
            }

            var commonProperties = GetCommonReadableProperties(unionTypes);
            intersections.Add(new IntersectionInfo(
                propertySymbol.Name,
                unionTypes.Select(static t => t.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)).ToImmutableArray(),
                commonProperties));
        }

        if (intersections.Count == 0)
        {
            return null;
        }

        return new Candidate(classSymbol, intersections.ToImmutableArray());
    }

    private static bool HasExperimentalTypingAttribute(INamedTypeSymbol classSymbol)
    {
        foreach (var attribute in classSymbol.GetAttributes())
        {
            var name = attribute.AttributeClass?.Name;
            if (name is "ExpermientalTypingAttribute" or "ExpermientalTyping")
            {
                return true;
            }
        }

        return false;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Candidate> candidates)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var candidate in candidates)
        {
            var classSymbol = candidate.ClassSymbol;
            var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString();

            var key = (ns ?? string.Empty) + "." + classSymbol.Name;
            if (!seen.Add(key))
            {
                continue;
            }

            var source = BuildSource(ns, classSymbol.Name, candidate.Intersections);
            context.AddSource(classSymbol.Name + ".ExperimentalTyping.g.cs", source);
        }
    }

    private static string BuildSource(string? ns, string className, ImmutableArray<IntersectionInfo> intersections)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("public partial class ").Append(className).AppendLine();
        sb.AppendLine("{");

        foreach (var intersection in intersections)
        {
            var memberNames = new HashSet<string>(StringComparer.Ordinal);
            var memberInfos = new List<(string TypeName, string MemberName)>();

            foreach (var typeName in intersection.TypeNames)
            {
                var baseName = ToSafeIdentifier(typeName);
                var uniqueName = baseName;
                var suffix = 2;
                while (!memberNames.Add(uniqueName))
                {
                    uniqueName = baseName + suffix;
                    suffix++;
                }

                memberInfos.Add((typeName, uniqueName));
            }

            sb.Append("    public ")
              .Append(intersection.PropertyName + "Type")
              .Append(" ")
              .Append(intersection.PropertyName + "Type")
              .AppendLine("Value => new();");
            sb.AppendLine();

            sb.Append("    public partial class ").Append(intersection.PropertyName + "Type").AppendLine();
            sb.AppendLine("    {");
            foreach (var memberInfo in memberInfos)
            {
                sb.Append("        public ").Append(memberInfo.TypeName).Append("? ").Append(memberInfo.MemberName).AppendLine(" { get; }");
            }
            sb.AppendLine();
            sb.Append("        public ").Append(intersection.PropertyName + "Type").AppendLine("()");
            sb.AppendLine("        {");
            foreach (var memberInfo in memberInfos)
            {
                sb.Append("            ").Append(memberInfo.MemberName).AppendLine(" = default;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.Append("        private ").Append(intersection.PropertyName + "Type").Append("(");
            for (var i = 0; i < memberInfos.Count; i++)
            {
                var parameterName = i == 0 ? "value" : "value" + (i + 1);
                if (i > 0)
                {
                    sb.Append(", ");
                }

                sb.Append(memberInfos[i].TypeName).Append("? ").Append(parameterName);
            }

            sb.AppendLine(")");
            sb.AppendLine("        {");
            for (var i = 0; i < memberInfos.Count; i++)
            {
                var parameterName = i == 0 ? "value" : "value" + (i + 1);
                sb.Append("            ").Append(memberInfos[i].MemberName).Append(" = ").Append(parameterName).AppendLine(";");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            for (var i = 0; i < memberInfos.Count; i++)
            {
                sb.Append("        public static implicit operator ").Append(intersection.PropertyName + "Type").Append("(").Append(memberInfos[i].TypeName).Append(" value) => new(");
                for (var j = 0; j < memberInfos.Count; j++)
                {
                    if (j > 0)
                    {
                        sb.Append(", ");
                    }

                    sb.Append(i == j ? "value" : "default");
                }

                sb.AppendLine(");");
            }

            sb.AppendLine();
            sb.Append("        [OneOf(");
            for (var i = 0; i < memberInfos.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }
                sb.Append("typeof(").Append(memberInfos[i].TypeName).Append(")");
            }
            sb.AppendLine(")]");
            sb.AppendLine("        public object GetValue()");
            sb.AppendLine("        {");
            foreach (var memberInfo in memberInfos)
            {
                sb.Append("            if (").Append(memberInfo.MemberName).AppendLine(" is not null)");
                sb.AppendLine("            {");
                sb.Append("                return ").Append(memberInfo.MemberName).AppendLine(";");
                sb.AppendLine("            }");
                sb.AppendLine();
            }
            sb.Append("            throw new InvalidOperationException(\"").Append(intersection.PropertyName + "Type").AppendLine(" has no value.\");");
            sb.AppendLine("        }");

            if (intersection.CommonProperties.Length > 0)
            {
                sb.AppendLine();
            }

            foreach (var property in intersection.CommonProperties)
            {
                sb.Append("        public ").Append(property.TypeName).Append(" ").Append(property.Name).AppendLine();
                sb.AppendLine("        {");
                sb.AppendLine("            get");
                sb.AppendLine("            {");
                foreach (var memberInfo in memberInfos)
                {
                    sb.Append("                if (").Append(memberInfo.MemberName).AppendLine(" is not null)");
                    sb.AppendLine("                {");
                    sb.Append("                    return ").Append(memberInfo.MemberName).Append(".").Append(property.Name).AppendLine(";");
                    sb.AppendLine("                }");
                    sb.AppendLine();
                }

                sb.Append("                throw new InvalidOperationException(\"").Append(intersection.PropertyName + "Type").AppendLine(" has no value.\");");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToSafeIdentifier(string typeName)
    {
        var simple = typeName;

        var lastDot = simple.LastIndexOf('.');
        if (lastDot >= 0 && lastDot < simple.Length - 1)
        {
            simple = simple.Substring(lastDot + 1);
        }

        var tickIndex = simple.IndexOf('`');
        if (tickIndex > 0)
        {
            simple = simple.Substring(0, tickIndex);
        }

        var sb = new StringBuilder(simple.Length);
        foreach (var ch in simple)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
            {
                sb.Append(ch);
            }
        }

        if (sb.Length == 0)
        {
            return "Value";
        }

        if (!char.IsLetter(sb[0]) && sb[0] != '_')
        {
            sb.Insert(0, '_');
        }

        return sb.ToString();
    }

    private static bool TryGetUnionTypes(ExpressionSyntax expression, SemanticModel semanticModel, out ImmutableArray<ITypeSymbol> types)
    {
        var all = ImmutableArray.CreateBuilder<ITypeSymbol>();
        FlattenOr(expression, semanticModel, all);

        var unique = ImmutableArray.CreateBuilder<ITypeSymbol>();
        foreach (var type in all)
        {
            if (!unique.Any(existing => SymbolEqualityComparer.Default.Equals(existing, type)))
            {
                unique.Add(type);
            }
        }

        types = unique.ToImmutableArray();
        return types.Length >= 2;
    }

    private static void FlattenOr(ExpressionSyntax expression, SemanticModel semanticModel, ImmutableArray<ITypeSymbol>.Builder types)
    {
        if (expression is BinaryExpressionSyntax binary && binary.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.BitwiseOrExpression))
        {
            FlattenOr(binary.Left, semanticModel, types);
            FlattenOr(binary.Right, semanticModel, types);
            return;
        }

        if (expression is not TypeOfExpressionSyntax typeOf)
        {
            return;
        }

        var type = semanticModel.GetTypeInfo(typeOf.Type).Type;
        if (type is not null)
        {
            types.Add(type);
        }
    }

    private static ImmutableArray<CommonPropertyInfo> GetCommonReadableProperties(ImmutableArray<ITypeSymbol> types)
    {
        if (types.Length == 0)
        {
            return ImmutableArray<CommonPropertyInfo>.Empty;
        }

        Dictionary<string, IPropertySymbol>? common = null;

        foreach (var type in types)
        {
            var properties = type
                .GetMembers()
                .OfType<IPropertySymbol>()
                .Where(static property => property.GetMethod is not null && !property.IsStatic && property.DeclaredAccessibility == Accessibility.Public && property.GetMethod.DeclaredAccessibility == Accessibility.Public)
                .ToDictionary(static property => property.Name, StringComparer.Ordinal);

            if (common is null)
            {
                common = properties;
                continue;
            }

            var next = new Dictionary<string, IPropertySymbol>(StringComparer.Ordinal);
            foreach (var kv in common)
            {
                if (properties.TryGetValue(kv.Key, out var candidate) &&
                    SymbolEqualityComparer.Default.Equals(kv.Value.Type, candidate.Type))
                {
                    next[kv.Key] = kv.Value;
                }
            }

            common = next;
            if (common.Count == 0)
            {
                break;
            }
        }

        if (common is null || common.Count == 0)
        {
            return ImmutableArray<CommonPropertyInfo>.Empty;
        }

        return common.Values
            .Select(static property => new CommonPropertyInfo(
                property.Name,
                property.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)))
            .OrderBy(static property => property.Name, StringComparer.Ordinal)
            .ToImmutableArray();
    }

    private sealed class Candidate
    {
        public Candidate(INamedTypeSymbol classSymbol, ImmutableArray<IntersectionInfo> intersections)
        {
            ClassSymbol = classSymbol;
            Intersections = intersections;
        }

        public INamedTypeSymbol ClassSymbol { get; }
        public ImmutableArray<IntersectionInfo> Intersections { get; }
    }

    private sealed class IntersectionInfo
    {
        public IntersectionInfo(string propertyName, ImmutableArray<string> typeNames, ImmutableArray<CommonPropertyInfo> commonProperties)
        {
            PropertyName = propertyName;
            TypeNames = typeNames;
            CommonProperties = commonProperties;
        }

        public string PropertyName { get; }
        public ImmutableArray<string> TypeNames { get; }
        public ImmutableArray<CommonPropertyInfo> CommonProperties { get; }
    }

    private sealed class CommonPropertyInfo
    {
        public CommonPropertyInfo(string name, string typeName)
        {
            Name = name;
            TypeName = typeName;
        }

        public string Name { get; }
        public string TypeName { get; }
    }
}
