using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ExperimnetalTypeSystem.Generator;

[Generator]
public sealed class ExperimentalTypingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax classDecl && classDecl.AttributeLists.Count > 0,
            static (ctx, _) => GetCandidate(ctx))
            .Where(static result => result is not null)
            .Select(static (result, _) => result!);

        context.RegisterSourceOutput(candidates.Collect(), static (spc, items) => Emit(spc, items));
    }

    private static Candidate? GetCandidate(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        if (!HasExperimentalTypingAttribute(classSymbol))
        {
            return null;
        }

        var intersections = new List<IntersectionInfo>();

        foreach (var member in classDecl.Members.OfType<PropertyDeclarationSyntax>())
        {
            if (member.ExpressionBody is null)
            {
                continue;
            }

            if (context.SemanticModel.GetDeclaredSymbol(member) is not IPropertySymbol propertySymbol)
            {
                continue;
            }

            if (propertySymbol.Type.Name != "UnionType")
            {
                continue;
            }

            if (member.ExpressionBody.Expression is not BinaryExpressionSyntax binary || binary.OperatorToken.Text != "|")
            {
                continue;
            }

            if (binary.Left is not TypeOfExpressionSyntax leftTypeOf || binary.Right is not TypeOfExpressionSyntax rightTypeOf)
            {
                continue;
            }

            var leftType = context.SemanticModel.GetTypeInfo(leftTypeOf.Type).Type;
            var rightType = context.SemanticModel.GetTypeInfo(rightTypeOf.Type).Type;

            if (leftType is null || rightType is null)
            {
                continue;
            }

            var commonProperties = GetCommonReadableProperties(leftType, rightType);
            intersections.Add(new IntersectionInfo(
                propertySymbol.Name,
                leftType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                rightType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                commonProperties));
        }

        if (intersections.Count == 0)
        {
            return null;
        }

        return new Candidate(classSymbol, intersections.ToImmutableArray());
    }

    private static bool HasExperimentalTypingAttribute(INamedTypeSymbol classSymbol)
    {
        foreach (var attribute in classSymbol.GetAttributes())
        {
            var name = attribute.AttributeClass?.Name;
            if (name is "ExpermientalTypingAttribute" or "ExpermientalTyping")
            {
                return true;
            }
        }

        return false;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Candidate> candidates)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var candidate in candidates)
        {
            var classSymbol = candidate.ClassSymbol;
            var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString();

            var key = (ns ?? string.Empty) + "." + classSymbol.Name;
            if (!seen.Add(key))
            {
                continue;
            }

            var source = BuildSource(ns, classSymbol.Name, candidate.Intersections);
            context.AddSource(classSymbol.Name + ".ExperimentalTyping.g.cs", source);
        }
    }

    private static string BuildSource(string? ns, string className, ImmutableArray<IntersectionInfo> intersections)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("public partial class ").Append(className).AppendLine();
        sb.AppendLine("{");

        foreach (var intersection in intersections)
        {
            var leftMemberName = ToSafeIdentifier(intersection.LeftName);
            var rightMemberName = ToSafeIdentifier(intersection.RightName);
            if (string.Equals(leftMemberName, rightMemberName, StringComparison.Ordinal))
            {
                rightMemberName += "2";
            }

            sb.Append("    public ")
              .Append(intersection.PropertyName + "Type")
              .Append(" ")
              .Append(intersection.PropertyName + "Type")
              .AppendLine("Value => new();");
            sb.AppendLine();

            sb.Append("    public partial class ").Append(intersection.PropertyName + "Type").AppendLine();
            sb.AppendLine("    {");
            sb.Append("        public ").Append(intersection.LeftName).Append("? ").Append(leftMemberName).AppendLine(" { get; }");
            sb.Append("        public ").Append(intersection.RightName).Append("? ").Append(rightMemberName).AppendLine(" { get; }");
            sb.AppendLine();
            sb.Append("        public ").Append(intersection.PropertyName + "Type").AppendLine("()")
              .AppendLine("        {")
              .Append("            ").Append(leftMemberName).AppendLine(" = default;")
              .Append("            ").Append(rightMemberName).AppendLine(" = default;")
              .AppendLine("        }");
            sb.AppendLine();
            sb.Append("        private ").Append(intersection.PropertyName + "Type").Append("(")
              .Append(intersection.LeftName).Append("? left, ")
              .Append(intersection.RightName).AppendLine("? right)")
              .AppendLine("        {")
              .Append("            ").Append(leftMemberName).AppendLine(" = left;")
              .Append("            ").Append(rightMemberName).AppendLine(" = right;")
              .AppendLine("        }");
            sb.AppendLine();
            sb.Append("        public static implicit operator ").Append(intersection.PropertyName + "Type").Append("(").Append(intersection.LeftName).AppendLine(" value) => new(value, default);");
            sb.Append("        public static implicit operator ").Append(intersection.PropertyName + "Type").Append("(").Append(intersection.RightName).AppendLine(" value) => new(default, value);");
            if (intersection.CommonProperties.Length > 0)
            {
                sb.AppendLine();
            }

            foreach (var property in intersection.CommonProperties)
            {
                sb.Append("        public ").Append(property.TypeName).Append(" ").Append(property.Name).AppendLine();
                sb.AppendLine("        {");
                sb.AppendLine("            get");
                sb.AppendLine("            {");
                sb.Append("                if (").Append(leftMemberName).AppendLine(" is not null)");
                sb.AppendLine("                {");
                sb.Append("                    return ").Append(leftMemberName).Append(".").Append(property.Name).AppendLine(";");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.Append("                if (").Append(rightMemberName).AppendLine(" is not null)");
                sb.AppendLine("                {");
                sb.Append("                    return ").Append(rightMemberName).Append(".").Append(property.Name).AppendLine(";");
                sb.AppendLine("                }");
                sb.AppendLine();
                sb.Append("                throw new InvalidOperationException(\"").Append(intersection.PropertyName + "Type").AppendLine(" has no value.\");");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToSafeIdentifier(string typeName)
    {
        var simple = typeName;

        var lastDot = simple.LastIndexOf('.');
        if (lastDot >= 0 && lastDot < simple.Length - 1)
        {
            simple = simple.Substring(lastDot + 1);
        }

        var tickIndex = simple.IndexOf('`');
        if (tickIndex > 0)
        {
            simple = simple.Substring(0, tickIndex);
        }

        var sb = new StringBuilder(simple.Length);
        foreach (var ch in simple)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
            {
                sb.Append(ch);
            }
        }

        if (sb.Length == 0)
        {
            return "Value";
        }

        if (!char.IsLetter(sb[0]) && sb[0] != '_')
        {
            sb.Insert(0, '_');
        }

        return sb.ToString();
    }

    private static ImmutableArray<CommonPropertyInfo> GetCommonReadableProperties(ITypeSymbol leftType, ITypeSymbol rightType)
    {
        var rightProperties = rightType
            .GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property => property.GetMethod is not null && !property.IsStatic && property.DeclaredAccessibility == Accessibility.Public && property.GetMethod.DeclaredAccessibility == Accessibility.Public)
            .ToDictionary(static property => property.Name, StringComparer.Ordinal);

        var properties = ImmutableArray.CreateBuilder<CommonPropertyInfo>();

        foreach (var leftProperty in leftType.GetMembers().OfType<IPropertySymbol>())
        {
            if (leftProperty.GetMethod is null ||
                leftProperty.IsStatic ||
                leftProperty.DeclaredAccessibility != Accessibility.Public ||
                leftProperty.GetMethod.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (!rightProperties.TryGetValue(leftProperty.Name, out var rightProperty))
            {
                continue;
            }

            if (!SymbolEqualityComparer.Default.Equals(leftProperty.Type, rightProperty.Type))
            {
                continue;
            }

            properties.Add(new CommonPropertyInfo(
                leftProperty.Name,
                leftProperty.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
        }

        return properties
            .OrderBy(static property => property.Name, StringComparer.Ordinal)
            .ToImmutableArray();
    }

    private sealed class Candidate
    {
        public Candidate(INamedTypeSymbol classSymbol, ImmutableArray<IntersectionInfo> intersections)
        {
            ClassSymbol = classSymbol;
            Intersections = intersections;
        }

        public INamedTypeSymbol ClassSymbol { get; }
        public ImmutableArray<IntersectionInfo> Intersections { get; }
    }

    private sealed class IntersectionInfo
    {
        public IntersectionInfo(string propertyName, string leftName, string rightName, ImmutableArray<CommonPropertyInfo> commonProperties)
        {
            PropertyName = propertyName;
            LeftName = leftName;
            RightName = rightName;
            CommonProperties = commonProperties;
        }

        public string PropertyName { get; }
        public string LeftName { get; }
        public string RightName { get; }
        public ImmutableArray<CommonPropertyInfo> CommonProperties { get; }
    }

    private sealed class CommonPropertyInfo
    {
        public CommonPropertyInfo(string name, string typeName)
        {
            Name = name;
            TypeName = typeName;
        }

        public string Name { get; }
        public string TypeName { get; }
    }
}
